let myArr = [0, 0, 0, 0, 0, 0];
undefined;
let randomElement = Math.ceil(Math.random() * 6);
undefined;
randomElement;
3;
myArr[3 - 1] = 0 + 1;
1;
myArr(6)[(0, 0, 1, 0, 0, 0)];
let randomElement = Math.ceil(Math.random() * 6);
undefined;
randomElement;
2;
myArr[randomElement - 1] = 0 + 1;
1;
myArr(6)[(0, 1, 1, 0, 0, 0)];
let randomElement = Math.ceil(Math.random() * 6);
undefined;
randomElement;
1;
myArr[randomElement - 1] = 0 + 1;
1;
myArr(6)[(1, 1, 1, 0, 0, 0)];
let randomElement = Math.ceil(Math.random() * 6);
undefined;
randomElement;
1;
myArr[randomElement - 1] = myArr[randomElement - 1] + 1;
2;
myArr(6)[(2, 1, 1, 0, 0, 0)];
myArr[randomElement - 1]++;
2;
myArr(6)[(3, 1, 1, 0, 0, 0)];
